name: CI Workflow

on:
 push:
  branches:
   - dev

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
  - name: Checkout Repo
    uses: actions/checkout@v2

  - name: Set up Python
    uses: actions/setup-python@v2
    with:
     python-version: '3.10'

  - name: Install Dependencies
    run: |
      pip install -q diffusers==0.25.0 xformers==0.0.25 einops ftfy basicsr facexlib insightface onnxruntime-gpu accelerate timm gradio apex
      # Fix for the torchvision import
      sed -i 's/from torchvision.transforms.functional_tensor import rgb_to_grayscale/from torchvision.transforms.functional import rgb_to_grayscale/' $(python -c "import site; print(site.getsitepackages()[0])")/basicsr/data/degradations.py

  - name: Clone Repository
    run: |
     git clone -b dev https://github.com/camenduru/PuLID-hf
     cd PuLID-hf
     wget https://huggingface.co/spaces/yanze/PuLID/resolve/main/eva_clip/bpe_simple_vocab_16e6.txt.gz -O eva_clip/bpe_simple_vocab_16e6.txt.gz

  - name: Run Application
    run: |
      cd PuLID-hf
      python app.py
